name: Update version pubspec

on:
  pull_request:
    types: opened
    branches:
      - develop
      - release**
    paths:
      - lib/**

permissions:
  contents: write
      
jobs:
  version: 
    uses: Theobernardon/theo-flutter/.github/workflows/majpubspec.yml@main
    with:
      commit_message: ${{ github.head_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
