name: 🧪 Tests Flutter

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theobernardon/theo-flutter/actions/test@main
